updated release script

diff --git a/bin/release b/bin/release
--- a/bin/release
+++ b/bin/release
@@ -1,10 +1,6 @@
 #!/bin/sh
 # call the apps release script
+set -o errexit    # always exit on error
 
-# this pack is valid for apps with a hello.txt in the root
-if [ -f $1/app/bin/release ]; then
-  $1/bin/release
-  exit $?
-else
-  exit 1
-fi
+$1/app/bin/release
+exit $?
